
name: Deploy To EC2

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Ec2
      - uses: appleboy/ssh-action@master
        with:
        host: ${{secrets.SSH_HOST}}
        username: e2c-user
        key: ${{secrets.SSH_PRIVATE_KEY}}
        script: |
          cd D:\phegonDev\phegon-bank
          git pull
          docker-compose up --build -d